[DOPS-1161] Add envoy-filter template to replace proxy-body-size annotation
matic-insurance/helm-charts pull request #80
Opened 2024-01-24 11:40 UTC by greykurotsuki

2024-01-24 12:20 UTC, volkorny approved these changes

2024-01-24 13:02 UTC, volodymyr-mykhailyk requested changes
From my understanding - this change will create such a filter for every project. Let's not do this and instead create filter only when someone specified body size limit. Also - please generate golden test for this use case.

2024-01-30 12:28 UTC, volodymyr-mykhailyk approved these changes
Looks good. Please take a look at my latest comments

2024-01-30 12:28 UTC, volodymyr-mykhailyk commented on stable/application-mesh/tests/golden/components/envoy-filter-max-body-size.values.yaml
> +    max_request_bytes: "67108864"
Why is this value a string? Is it required? What happens if I don't specify quotes

2024-01-30 12:28 UTC, volodymyr-mykhailyk commented on stable/application-mesh/tests/golden/components/envoy-filter-max-body-size.values.yaml
> +    max_request_bytes: "67108864"
I would recommend adding one level of nesting here and making a key a bit more clear:
```
- host: leads-broker.matic.com
   settings:
     max_request_size_bytes: 1234
```

2024-01-30 12:28 UTC, volodymyr-mykhailyk commented on stable/application-mesh/tests/golden/golden_test.go
> +			Templates: []string{"templates/envoy-filter.yaml", "templates/virtual-service.yaml"},
Something is off with indent

2024-01-30 12:28 UTC, volodymyr-mykhailyk commented on stable/application-mesh/tests/golden/components/envoy-filter-max-body-size.golden.yaml
> +---
While this is a component test - it includes other templates. Something is off

2024-01-30 12:50 UTC, greykurotsuki commented on stable/application-mesh/tests/golden/components/envoy-filter-max-body-size.values.yaml
> +    max_request_bytes: "67108864"
It is necessary to use quotes to specify the exact value. For instance, when you specify `max_request_bytes: 67108864`, Helm translates it to `max_request_bytes: 6.7108864e+07`.

2024-01-30 13:08 UTC, greykurotsuki commented on stable/application-mesh/tests/golden/golden_test.go
> +			Templates: []string{"templates/envoy-filter.yaml", "templates/virtual-service.yaml"},
Thanks for noticing.

2024-01-30 13:35 UTC, volodymyr-mykhailyk commented on stable/application-mesh/tests/golden/components/envoy-filter-max-body-size.values.yaml
> +    max_request_bytes: "67108864"
In this case, you should transform it to int representation when rendering. I assure you, next time someone edits this setting - they will forget to add quotes

2024-01-30 14:08 UTC, merged